apiVersion: v1
kind: Service
metadata:
  name: {{ include "qserv.name" . }}-czar
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  selector:
    {{- include "qserv.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: czar
  ports:
    - name: czar-http
      port: 4048
      targetPort: czar-http
    - name: mysql-proxy-ssl
      port: 4040
      targetPort: mysql-proxy-ssl
