apiVersion: v1
kind: Service
metadata:
  name: {{ include "qserv.name" . }}-repl
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  selector:
    {{- include "qserv.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: repl
  {{- if (include "qserv.enable" . | fromYaml).replication }}
  ports:
    - name: http
      port: 25081
      targetPort: http
  {{- end }}
