apiVersion: v1
kind: Service
metadata:
  name: {{ include "qserv.name" . }}-worker
  labels:
    {{- include "qserv.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  publishNotReadyAddresses: true
  selector:
    {{- include "qserv.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
